-- Reprend profile/experience/skills/education déjà présents dans src/lib/data.ts.
-- À exécuter APRÈS la partie profile/experience/skill_groups/education de schema.sql,
-- une seule fois (sinon experience/skill_groups/education seront dupliqués — profile
-- utilise UPSERT donc peut être ré-exécuté sans risque).

-- profile (singleton row, id = 1)
insert into public.profile (id, name, role, tagline, location, email, github_url, linkedin_url, summary, about_description, stats) values (1, 'Brandon Daniel Medehou', 'Développeur Front-End & Data', 'React / Next.js · Python & APIs', 'Cotonou, Bénin · Mobile / full remote', 'brandonmedehou2203@gmail.com', 'https://github.com/Brandon22030', 'https://linkedin.com/in/brandon-medehou', 'Développeur front-end avec 2 ans d''expérience professionnelle et plus de 4 applications web livrées en production (Next.js, React, TypeScript). Je construis aussi les APIs Python et les modèles de données qui alimentent ces interfaces : modules comptables Odoo manipulant de gros volumes sur PostgreSQL, route d''API centralisée sur AWS API Gateway, dashboard d''analyse de données bancaires à la Société Générale Bénin. Attaché à la performance (Core Web Vitals), à la qualité du rendu et à la lisibilité des données restituées. Fort intérêt pour l''IA appliquée aux produits.', 'Un profil qui relie l''interface et la donnée : je construis les écrans, mais aussi les APIs et les modèles qui les nourrissent.', '[{"value":"2+","label":"Ans d''expérience"},{"value":"4+","label":"Apps en production"},{"value":"Front-end & Data","label":"Stack"}]'::jsonb)
  on conflict (id) do update set name = excluded.name;

-- experience
insert into public.experience (company, role, period, location, highlights, sort_order) values ('ADELABS', 'Développeur Front-End & Odoo', 'juin 2025 — août 2026', 'Cotonou, Bénin', array['Développé des modules et APIs Python (Odoo) dans le périmètre comptable : extraction et restitution de gros volumes de données sur PostgreSQL — exports FEC multi-formats, reconstitution d''inventaires à date, déclarations de TVA.', 'Mis en place une route POST sur AWS API Gateway pour centraliser et fiabiliser le traitement des formulaires web de plusieurs sites livrés.', 'Conçu et livré 4+ applications web en production avec Next.js et Strapi : interfaces React/TypeScript, modélisation des contenus et intégration d''APIs REST.', 'Optimisé la performance et les Core Web Vitals (LCP, CLS) via le choix du mode de rendu SSR/SSG et l''optimisation des images.', 'Testé et validé les APIs REST avec Postman avant intégration : codes HTTP, formats de réponse et gestion des cas d''erreur.', 'Diagnostiqué et corrigé des incidents applicatifs et anomalies de données en production sur PostgreSQL/Odoo, en collaboration directe avec les utilisateurs métier.', 'Mis en œuvre le SEO technique des sites livrés : JSON-LD/Schema.org, Metadata API de Next.js, Open Graph, balises canoniques, sitemap.xml et robots.txt.'], 0);
insert into public.experience (company, role, period, location, highlights, sort_order) values ('Société Générale Bénin', 'Stagiaire Développeur Web', 'nov. 2024 — mars 2025', 'Cotonou, Bénin', array['Développé un dashboard interactif d''analyse de données bancaires : agrégation des données, rapports détaillés et visualisations dynamiques conçus avec et pour les équipes métier.'], 1);
insert into public.experience (company, role, period, location, highlights, sort_order) values ('Vertim Coders', 'Stagiaire Développeur Web', 'janv. 2024 — avr. 2024', 'Tankpè, Bénin', array['Intégré des interfaces Vue.js à partir de maquettes en respectant les contraintes d''ergonomie, et mis en ligne des sites WordPress (PHP) pour les clients de l''agence.'], 2);
insert into public.experience (company, role, period, location, highlights, sort_order) values ('Freelance', 'Développeur & Designer indépendant', '2023 — 2024', 'Cotonou, Bénin', array['Développement de sites, thèmes et extensions WordPress sur mesure (PHP) pour différents clients.', 'Conception de maquettes d''interfaces sous Figma, création d''identités visuelles et de supports graphiques.'], 3);

-- skill_groups
insert into public.skill_groups (category, items, sort_order) values ('Front-end & UI', array['Next.js', 'React.js', 'TypeScript', 'JavaScript', 'Vue.js', 'Tailwind CSS', 'HTML sémantique', 'CSS/SCSS', 'Figma'], 0);
insert into public.skill_groups (category, items, sort_order) values ('Back-end & APIs', array['Python (modules et routes Odoo)', 'Node.js', 'NestJS', 'Express.js', 'PHP (WordPress)', 'APIs REST (Postman)'], 1);
insert into public.skill_groups (category, items, sort_order) values ('Données', array['PostgreSQL', 'MySQL', 'MongoDB', 'Supabase', 'Modélisation & agrégation', 'Exports & dashboards'], 2);
insert into public.skill_groups (category, items, sort_order) values ('Performance & qualité', array['Core Web Vitals (LCP, CLS)', 'SSR/SSG', 'Optimisation d''images', 'Diagnostic prod'], 3);
insert into public.skill_groups (category, items, sort_order) values ('Cloud & outils', array['AWS API Gateway', 'Docker', 'Git / GitHub', 'PageSpeed Insights', 'Google Search Console'], 4);
insert into public.skill_groups (category, items, sort_order) values ('SEO technique', array['JSON-LD / Schema.org', 'Metadata API Next.js', 'Open Graph', 'sitemap.xml', 'robots.txt'], 5);

-- education
insert into public.education (title, school, period, sort_order) values ('Certification Développeur Fullstack', 'Coding Academy by EPITECH · Cotonou, Bénin', 'juin 2024 — juin 2025', 0);
insert into public.education (title, school, period, sort_order) values ('Licence 3 d''Anglais', 'Faculté des Lettres, Langues et Arts de Calavi (FLLAC) · Abomey-Calavi, Bénin', '2021 — 2024', 1);
insert into public.education (title, school, period, sort_order) values ('Certificat en Compétences Numériques Fondamentales', 'ECOLE229 · Cotonou, Bénin', '2023 — 2024', 2);
