-- Reprend les 13 projets déjà présents dans src/lib/data.ts.
-- À exécuter APRÈS schema.sql, une seule fois (sinon les projets seront dupliqués).
-- dans le SQL editor de ton projet Supabase.

insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('Lokata', 'Plateforme de location de matériel informatique, conçue et développée seul, du cahier des charges au produit : modélisation des données, authentification, et spécification d''un agent de sécurité poste client (isolation de session, signature Ed25519).', array['Next.js', 'TypeScript', 'Supabase'], null, null, null, 0);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('Intégration d''IA générative', 'Intégration d''APIs de modèles de langage dans des applications personnelles (planification quotidienne, génération de contenus), avec traitement des réponses structurées et gestion des erreurs côté back-end.', array['LLM APIs', 'Node.js', 'Réponses structurées'], null, null, null, 1);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('La Cité Du Rancard', 'Plateforme de gestion d''événements et de réseautage social pour organiser et promouvoir des événements à Cotonou, Bénin : vente de billets, réservation de stands, gestion de partenaires et matchmaking entre participants.', array['React', 'TypeScript', 'TailwindCSS', 'Vite', 'Supabase', 'Cloudinary', 'Moneroo'], 'https://www.lacitedurancard.com/', null, null, 2);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('Fairy Dust Portfolio', 'Site portfolio professionnel pour une assistante virtuelle, présentée sous le nom ''La Petite Fée de l''Assistance Virtuelle''.', array['React', 'TypeScript', 'TailwindCSS', 'Vite'], 'https://stevie-alyda.netlify.app/', null, null, 3);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('Benin Culture 360', 'Application web interactive pour explorer et découvrir la riche culture béninoise.', array['React', 'TypeScript', 'TailwindCSS', 'Supabase'], 'https://benin-culture-360.pages.dev/', 'https://github.com/Brandon22030/benin-culture-360', null, 4);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('BlogHub', 'Plateforme de blogging moderne construite avec un backend NestJS et un frontend Next.js.', array['NestJS', 'Next.js', 'MongoDB', 'Prisma', 'TailwindCSS', 'TypeScript'], 'https://bloghub-vdm6.onrender.com/', 'https://github.com/Brandon22030/BlogHub', 'https://www.figma.com/design/xrWs7bMQsRRWRAmKUu7JuP/Blog-Hub?node-id=0-1&t=QHQJrF0wZm3ipHvR-1', 5);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('Festivalis', 'Plateforme d''événements communautaires conçue spécifiquement pour le Bénin.', array['React', 'TypeScript', 'Vite', 'TailwindCSS', 'Supabase'], null, 'https://github.com/Brandon22030/Festivalis', null, 6);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('HeritageGourmet', 'Application web dédiée à la préservation et au partage des recettes familiales.', array['React', 'TypeScript', 'Vite', 'Supabase', 'TailwindCSS'], null, 'https://github.com/brandy-the-dev/heritage-gourmet', null, 7);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('Trello WordPress', 'Ajout et affichage de tâches avec Vue.js et Pinia, en s''appuyant sur l''API REST de WordPress.', array['Vue.js', 'Pinia', 'TailwindCSS', 'WordPress REST API'], null, 'https://github.com/Brandon22030/Trello-WordPress', null, 8);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('YOWL', 'Application permettant de commenter tout ce qui se passe sur Internet.', array['Vue.js', 'Pinia', 'TailwindCSS', 'Laravel', 'MySQL', 'Docker'], null, 'https://github.com/Brandon22030/yowl', null, 9);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('LavoTech', 'Plateforme de services de pressing en ligne : réservation, suivi de commande en temps réel et approche écologique.', array['React', 'TypeScript', 'TailwindCSS', 'Vite', 'Supabase'], null, 'https://github.com/Brandon22030/lavoTech', null, 10);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('SGAMA', 'Système de Gestion d''Atelier Mécanique Automobile : rendez-vous, véhicules, interventions et relation client.', array['React', 'TypeScript', 'TailwindCSS', 'Vite', 'Supabase'], null, 'https://github.com/Brandon22030/SGAMA', null, 11);
insert into public.projects (name, description, stack, live_url, github_url, figma_url, sort_order) values ('RoboGenius Lab', 'Plateforme éducative pour l''apprentissage de la robotique : parcours personnalisés, simulateur interactif et ressources pédagogiques.', array['React', 'TypeScript', 'TailwindCSS', 'Vite', 'Supabase'], null, 'https://github.com/Brandon22030/RoboGenius-Lab', null, 12);
